### ISSUE TITLE
Button style

### ISSUE THREAD

**Issue by Aaron-Bird** [Aaron-Bird/notebook#1]
![2018-10-18_19-22-11](https://user-images.githubusercontent.com/25508292/47157278-8ee8cf80-d31b-11e8-9ecc-7033b59d5ce0.gif)

```html
<button>Play</button>
```
```css
button {
    position: relative;
    overflow: hidden;
    width: 90px;
    height: 50px;
    padding: 0;
    font-family: inherit;
    font-size: 20px;
    font-weight: 500;
    cursor: pointer;
    transition: .2s ease-out;
    letter-spacing: 4px;
    color: #fff;
    border: 1px solid rgb(59, 153, 197);
    border-radius: 4px;
    outline: 0;
    background: rgb(59, 153, 197);
    box-shadow: 0 0 8px 0 rgba(59, 153, 197, .4);
    text-shadow: 0 0 10px rgb(0, 0, 0, .2);
}

button:hover {
    width: 80px;
    height: 80px;
    margin-top: -15px;
    margin-left: 5px;
    color: rgb(59, 153, 197);
    border: 0;
    border-radius: 100%;
}

button:before {
    position: absolute;
    top: 50%;
    left: 50%;
    display: block;
    width: 0;
    height: 0;
    font-size: 0;
    line-height: 80px;
    content: '♫';
    transform: translate(-50%, -50%);
    border-radius: 100%;
    background: inherit;
}

button:hover:before {
    width: 100%;
    height: 100%;
    font-size: 30px;
    color: #fff;
}

button:after {
    position: absolute;
    z-index: 1;
    top: 50%;
    left: 50%;
    display: block;
    width: 0;
    height: 0;
    content: '';
    transition: .4s ease-in-out;
    transform: translate(-50%, -50%);
    border-radius: 100%;
    background: rgba(255,255,255,.1);
}

button:hover:after {
    width: 150%;
    height: 150%;
    font-size: 30px;
    color: #fff;
}
```

**Comment by Aaron-Bird** [comment]
![2018-10-19_02-07-09](https://user-images.githubusercontent.com/25508292/47174714-fa469780-d343-11e8-8c71-c611f76c88e5.gif)

```html
<div class="button">
    <span>Play</span>
    <div class="dot-1"></div>
    <div class="dot-2"></div>
    <div class="dot-3"></div>
    <div class="dot-4"></div>
    <div class="dot-5"></div>
    <div class="dot-6"></div>
    <div class="circle-1"></div>
    <div class="circle-2"></div>
    <div class="circle-3"></div>
</div>
```
```css

.button {
    position: relative;
    display: inline-block;
    box-sizing: border-box;
    width: 180px;
    height: 60px;
    font-size: 20px;
    font-weight: 700;
    cursor: pointer;
    user-select: none;
    transition: .4s ease;
    text-align: center;
    letter-spacing: 2px;
    color: #fff;
    border-radius: 8px;
    background-image: linear-gradient(60deg, #29323c 0%, #485563 100%);
    box-shadow: 0 0 40px -5px #29323c;
}

/* Centered text */
.button:before {
    display: inline-block;
    width: 0;
    height: 100%;
    content: '';
    vertical-align: middle;
}

.button:hover {
    transform: scale(0.9);
    box-shadow: 0 0 20px -5px #29323c;
}

.button div[class|='dot'],
.button div[class|='circle'] {
    position: absolute;
    z-index: -1;
    top: 50%;
    left: 50%;
    /* Hide animation when the mouse moves out of the button */
    transition: 0;
    transform: translate(-50%, -50%);
    border-radius: 100%;
}

.button div[class|='dot'] {
    width: 6px;
    height: 6px;
    background: #37414C;
}

.button div[class|='circle'] {
    width: 20px;
    height: 20px;
    border: 1px solid #37414C;
}

.button:hover div[class|='dot'],
.button:hover div[class|='circle'] {
    transition: 1s ease-out;
    opacity: 0;
}


.button:hover div.dot-1 {
    top: -100%;
    left: 15%;
    transition-duration: .6s;
}

.button:hover div.dot-2 {
    top: -150%;
    left: 50%;
    transition-duration: .8s;
}

.button:hover div.dot-3 {
    top: -130%;
    left: 90%;
    transition-duration: .6s;
}

.button:hover div.dot-4 {
    top: 200%;
    left: 70%;
    transition-duration: 1s;
}

.button:hover div.dot-5 {
    top: 300%;
    left: 40%;
    transition-duration: .8s;
}

.button:hover div.dot-6 {
    top: 120%;
    left: 80%;
    transition-duration: .6s;
}

.button:hover div.circle-1 {
    top: -200%;
    left: 40%;
    transition-duration: .8s;
}

.button:hover div.circle-2 {
    top: 150%;
    left: 10%;
    transition-duration: .6s;
}
.button:hover div.circle-3 {
    top: 260%;
    left: 90%;
    transition-duration: .6s;
}
```

**Comment by Aaron-Bird** [comment]
![2018-10-19_16-11-19](https://user-images.githubusercontent.com/25508292/47205949-ffdec480-d3b9-11e8-9b57-fdec29152c91.gif)

```html
<div class="input" contenteditable="true"></div>
```
```css
.input {
    position: relative;
    display: inline-block;
    overflow: hidden;
    box-sizing: border-box;
    width: 60px;
    height: 60px;
    padding-left: 20px;
    font-size: 22px;
    line-height: 60px;
    cursor: pointer;
    transition: .6s ease;
    color: #fff;
    border: 1px solid rgb(20, 216, 240);
    border-radius: 60px;
    outline: 0;
    background: rgb(20, 216, 240);
    box-shadow: 0 0 0 3px rgb(10, 206, 230),
    0 0 40px 0 rgba(10, 206, 230, .8),
    inset 0 0 4px 0 rgba(0,0,0,.2);
}

.input:after {
    position: absolute;
    top: 1px;
    right: 1px;
    display: inline-block;
    box-sizing: border-box;
    width: 56px;
    height: 56px;
    font-size: 26px;
    font-weight: 700;
    line-height: 46px;
    content: '★';
    transition: inherit;
    text-align: center;
    word-wrap: nowrap;
    color: #fff;
    border: 4px solid rgba(255, 255, 255, .1);
    border-radius: 100%;
    background: rgb(10, 206, 230);
    box-shadow: 0 0 20px -5px rgba(0,0,0, .9),
    inset 0 0 10px 0 rgba(0,0,0,.1);
}

.input:hover,
.input:focus {
    width: 300px;
    height: 60px;
}

.input:hover:after,
.input:focus:after {
    transform: rotate(360deg);
    background: rgb(255, 255, 255, .1);
    box-shadow: 0 0 20px -5px rgba(0, 0, 0, .8),
    inset 0 0 10px 0 rgba(0,0,0,.1);
}
```

**Comment by Aaron-Bird** [comment]
![2018-10-27_15-41-07](https://user-images.githubusercontent.com/25508292/47601174-0ba43980-d9ff-11e8-8ee5-5c802c64f9eb.gif)
```html
<label for="test">
    <input type="checkbox" id="test">
    <span class="checkbox"></span>
</label>
```

```css
label {
    cursor: pointer;
    user-select: none;
}

input {
    display: none;
}

.checkbox {
    position: relative;
    display: inline-block;
    width: 40px;
    height: 40px;
    user-select: none;
    vertical-align: middle;
    border: 3px solid #343434;
    box-shadow: 0 0 40px -5px rgba(0, 0, 0, .1);
    overflow: hidden;
}

.checkbox:before {
    display: block;
    width: 100%;
    height: 100%;
    font-size: 40px;
    content: '';
    transition: .2s;
    opacity: 0;
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAQAAABIkb+zAAABJUlEQVR4Ae3UgUZEURSF4aO5epQg5O79CL1AgUCIECEMAhTQcwQCknGDCb1YOiUs5HKagTlL/38fYH/L5RQiIiIiIiIiIvrdeGzNz8eseenNr1nj2pivCa58fUtfviZ482vcm/DjCT58+PDh/yP+njv/GT58+PDhb9LCnJ8T/O2K03wpgy0/T/Ija05lYcmPsx9+1QQv/ngenzqpCZ58TbDhHx3Mnl6VDYrVLvgqLubO5/THF2no4N0fr7aeMOR6p/zGhHUZLPitCQb81gQDfmOCAb8xoXe+ypvGhL757QmH+33zGxO++e8981UuZye8xluD3/1fcOFrgi9fEyz5ary15muCL18TfPma4MvXBEu+ijtXvsoHX74mePH9IyIiIiIiIvoCNddudozLkb4AAAAASUVORK5CYII=) no-repeat;
    background-size: 40px;
}

input:checked+.checkbox:before {
    opacity: 1;
}
```

**Comment by Aaron-Bird** [comment]
![scroll4](https://user-images.githubusercontent.com/25508292/48308110-614c1a80-e597-11e8-8c04-0b15161c7f2c.gif)

```html
<label class="switch" for="s">
    <input type="checkbox" id="s">
    <span></span>
</label>
```

```css
body {
    padding: 100px;
}

.switch {
    position: relative;
    display: inline-block;
    width: 160px;
    height: 60px;
    border-radius: 60px;
    background: #eee;
    box-shadow: 0 0 40px -5px rgba(0,0,0,.1);
}

.switch input {
    display: none;
}

.switch input + span {
    position: absolute;
    top: 50%;
    left: 5px;
    display: inline-block;
    overflow: hidden;
    width: 50px;
    height: 50px;
    content: '';
    cursor: pointer;
    transition: .4s ease;
    transform: translateY(-50%);
    border-radius: 60px;
    background: rgba(255,255,255,.6);

    will-change: left;
}

.switch input:checked + span {
    left: calc(100% - 50px - 5px);
    transform: translateY(-50%) rotate(360deg);
    background: rgba(255,255,255, .8);
    box-shadow: 0 0 10px -5px rgba(0,0,0,.1);
}

.switch input + span:before {
    position: absolute;
    top: 49%;
    left: 50%;
    font-size: 16px;
    content: '✘';
    transition: .4s ease;
    transform: translate(-50%, -50%);
    color: rgba(0,0,0,.6);
}

.switch input:checked + span:before {
    position: absolute;
    top: 49%;
    left: 50%;
    font-size: 16px;
    content: '✔';
    transform: translate(-50%, -50%);
}
```

**Comment by Aaron-Bird** [comment]
![p](https://user-images.githubusercontent.com/25508292/50257042-60c75f00-0434-11e9-8d63-1231ba3a6f94.gif)
```html

<label class="container">
  <input type="checkbox">
  <ul>
    <li class="i-1 icon" data-content="a" onclick="console.log(1)">
    </li>
    <li class="i-2 icon" data-content="b" onclick="console.log(2)">
    </li>
    <li class="i-3 icon" data-content="c" onclick="console.log(3)">
    </li>
    <li class="i-0 icon" data-content="+">
    </li>
  </ul>
</label>
<!--author: Lucas Bebber  -->
<!--link: https://tympanus.net/codrops/2015/03/10/creative-gooey-effects/  -->
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" style="display: none">
  <defs>
    <filter id="goo">
      <feGaussianBlur in="SourceGraphic" stdDeviation="10" result="blur" />
      <feColorMatrix in="blur" mode="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9"
        result="goo" />
      <feComposite in="SourceGraphic" in2="goo" operator="atop" />
    </filter>
  </defs>
</svg>
```
```css
.container {
  display: inline-block;
  position: relative;
  padding: 10px;
  width: 60px;
  height: 60px;
  -webkit-filter: url("#goo");
  filter: url("#goo");
  input {
    display: none;
  }
  ul {
    list-style: none;
    li {
      position: absolute;
      top: 10px;
      left: 10px;
      cursor: pointer;
      width: 60px;
      height: 60px;
      background: #000;
      border-radius: 50%;
      transition: left 0.4s cubic-bezier(0, .99, .48, 1.31), transform 0.4s;
      &.i-0 {
        transition: opacity 0.4s steps(1, end), transform 0.4s;
      }
      &:hover {
        transform: scale(1.1);
      }
    }
  }
  input:checked+ul {
    li {
      transform: scale(0.8);
      &:hover {
        transform: scale(0.9);
      }
      &.i-0 {
        display: none;
        opacity: 0;
        transition: opacity 0s;
      }
      &.i-1 {
        left: -60px;
      }
      &.i-3 {
        left: 80px;
      }
    }
  }
}

.icon:before {
  display: block;
  content: attr(data-content);
  color: #ff0;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  font-size: 20px;
  line-height: 60px;
  text-align: center;
}
```

**Comment by Aaron-Bird** [comment]
![p](https://user-images.githubusercontent.com/25508292/50368754-217d4780-05c7-11e9-9b1c-0e807f76191f.gif)
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/89/three.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tween.js/16.3.5/Tween.min.js"></script>
<label class="container">
  <input type="checkbox">
  <canvas></canvas>
  <div></div>
</label>
```
```scss
.container {
  position: relative;
  display: inline-block;
  width: 160px;
  height: 80px;
  border-radius: 60px;
  overflow: hidden;
  box-shadow: 0 15px 40px -5px rgba(255, 59, 76, 0.2);
  transition: transform 0.4s, box-shadow 0.4s;
  cursor: pointer;
  input {
    display: none;
  }
  canvas {
    width: 100%;
    height: 100%;
    background: rgb(255, 59, 76);
    transition: background 0.4s ease 0.1s;
  }
  input:checked+canvas {
    background: rgb(0, 239, 139);
  }
  &.greenShadow {
    box-shadow: 0 15px 40px -5px rgba(0,239,139, 0.2);
  }
  .wave {
    position: absolute;
    top: 50%;
    transform: translate(-50%, -50%);
    left: 115px;
    width: 0px;
    height: 0px;
    z-index: 10;
    background: rgba(255, 255, 255, 0.3);
    border-radius: 100%;
    animation: wave 0.4s ease;  
  }
  input:checked~.wave {
    left: 45px;
  }
}

@keyframes wave{
  0% {
    width: 0px;
    height: 0px;
  }  
  100% {
    width: 300px;
    height: 300px;
  }
}
```

```js
var container = document.querySelector('.container');
var input = container.querySelector('input');
var div = container.querySelector('div');
var cvs = container.querySelector('canvas');
var [width, height] = [container.offsetWidth, container.offsetHeight];
var position = { x: -3.6, ry: 0 };

function initTorus() {
  var renderer = new THREE.WebGLRenderer({
    canvas: cvs,
    antialias: true,
    alpha: true
  });
  // set
  renderer.setSize(width, height);
  renderer.setClearColor(0x000000, 0);
  renderer.setPixelRatio(window.devicePixelRatio);
  // scene
  var scene = new THREE.Scene();
  // camera
  var camera = new THREE.PerspectiveCamera(45, width / height, 1, 50);
  camera.position.set(0, 0, 10);
  scene.add(camera);
  // torus
  var geometry = new THREE.TorusGeometry(2, 0.8, 10, 30);
  var material = new THREE.MeshLambertMaterial({
    color: '#ffffff',
    emissive: 0xffffff
  });
  var torus = new THREE.Mesh(geometry, material);
  torus.position.x = position.x;
  torus.castShadow = true;
  scene.add(torus);
  // update
  function updateTorus() {
    torus.position.x = position.x;
    torus.rotation.y = position.ry;
  }
  // animation
  function animate() {
    TWEEN.update();
    updateTorus();
    requestAnimationFrame(animate);
    renderer.render(scene, camera);
  }
  animate();
}

function initClickEnt() {
  var tween = new TWEEN.Tween(position).easing(TWEEN.Easing.Bounce.Out);
  input.addEventListener('click', function(event) {
    if (input.checked) {
      tween.to({ x: 3.6, ry: Math.PI * 0.4 }, 1200);
      container.classList.add('greenShadow');
      div.classList.remove('wave');
      div.clientLeft;
      div.classList.add('wave');
    } else {
      tween.to({ x: -3.6, ry: 0 }, 1200);
      container.classList.remove('greenShadow');
      div.classList.remove('wave');
      div.clientLeft;
      div.classList.add('wave');

    }
    tween.start();
  }, true);
  var timer, scale = 1;
  container.addEventListener('mousedown', function(event) {
    timer = setInterval(function() {
      if (scale > 0.9) {
        scale -= 0.04;
        container.style.transform = `scale(${scale})`
      }
    }, 10);
  });
  container.addEventListener('mouseup', function(event) {
    if (timer) {
      clearInterval(timer);
      scale = 1;
      container.style.transform = 'none';
    }
  });
}

initTorus();
initClickEnt();
```
