### ISSUE TITLE
层叠上下文(stacking context)

### ISSUE THREAD

**Issue by Aaron-Bird** [Aaron-Bird/notebook#2]
## 什么是层叠上下文?
层叠上下文是一个概念,渲染时根据层叠上下文的顺序,决定如何处理元素z轴位置   
每个元素都属于一个层叠上下文.有一个层叠顺序值,表示元素在当前层叠上下文中的z轴位置  
层叠上下文中的元素根据层叠顺序从下到上依次排列.如果层叠顺序相同,则根据元素在文档中的顺序排列   

## 哪些属性会创建层叠上下文?
- position: fixed | sticky
- position: relative | absolute, z-index值不为auto
- flex | inline-flex, z-index值不为auto
- opacity值小于1
- filter值不为none
- transform值不为none
- mix-blend-mode值不为normal
- isolation: isolate
- will-change值不为auto
- perspective值不为none
- -webkit-overflow-scrolling: touch

## 生成层叠上下文的元素及其后代的绘制顺序(从后到前)
- 元素的边框和背景
- z-index为负且形成层叠上下文的后代元素
- 文本流内的非内联块级元素
- position值为static的浮动元素
- 文本流内的内联元素
- position值不为static的元素; z-index值为0或auto且形成层叠上下文的后代元素
- z-index为正且形成层叠上下文的后代元素

# z-index

默认值: auto  
适用元素: position值不为static的元素  

![stack](https://user-images.githubusercontent.com/25508292/48082200-e13b5300-e22c-11e8-941f-2b6c921f5f0a.png)  
  
## z-index的作用是什么?  
1 设置元素在当前"层叠上下文"中的z轴位置(stack level)  
2 创建局部层叠上下文(local stacking contexts)  

注意   
1 position值为absolute | relative的元素需搭配z-index,才会创建层叠上下文   
![5339a03e](https://user-images.githubusercontent.com/25508292/48043766-465a5e80-e1c3-11e8-9d47-2b79d3c9e94e.png)

```html
<div class="container">
    <div class="child-1"><span>test</span></div>
    <div class="child-2"></div>
</div>
<style>
    .child-1 {
        width: 100px;
        height: 50px;
        position: absolute;
        border: 4px solid blue;
    }
    span {
        position: relative;
        z-index: -1;
    }
    .child-2 {
        width: 200px;
        height: 50px;
        background: rgba(255,255,0,0.9);
    }
</style>
```
.child-1边框颜色为蓝色,内有文字test, .child-2背景颜色为半透明黄色
.child-1虽然在.child-2上,但并没形成层叠上下文.导致其内部文字跑到了.child-2后面  

2 z-index只能用于position值不为static的元素,对position值为static的元素无效  
![7fa28b7d](https://user-images.githubusercontent.com/25508292/48043770-4c503f80-e1c3-11e8-9834-f2c9692e465a.png)

 ```html
<div class="container">
    <div class="child-1"><span>test</span></div>
    <div class="child-2"></div>
</div>
<style>
    .container {
        width: 200px;
        background: #efefef;
    }
    .child-1 {
        width: 100px;
        height: 50px;
        border: 4px solid blue;
        isolation: isolate;
        z-index: 1;
        margin-bottom: -20px;
    }
    span {
        position: relative;
        z-index: -1;
    }
    .child-2 {
        width: 200px;
        height: 50px;
        background: rgba(255, 255,0, 0.9);
        position: relative;
    }    
</style>
 ```
 .container背景颜色为灰色,.child-1边框颜色为蓝色,内有文字test, .child-2背景颜色为半透明黄色
 .child-1使用属性isolation: isolate创建层叠上下文, 因此.child-1的文字没有跑到背景下面去
 但.child-1的z-index没有生效,.child-1在.child-2下面
 
 ## 参考
 [W3C CSS2 z-index](https://www.w3.org/TR/CSS22/visuren.html#z-index)  
 [W3C css-position-3 Detailed stacking context](https://www.w3.org/TR/css-position-3/#det-stacking-context)  
 [MDN 层叠上下文](https://developer.mozilla.org/zh-CN/docs/Web/Guide/CSS/Understanding_z_index/The_stacking_context)  
 [MDN z-index](https://developer.mozilla.org/zh-CN/docs/Web/CSS/z-index)

**Comment by Aaron-Bird** [comment]
![default](https://user-images.githubusercontent.com/25508292/48081817-e055f180-e22b-11e8-8f11-40bbe61673a9.PNG)

```html
<div class="container">
    <div class="z-index-positive">z-index: 1</div>
    <div class="z-index-zero">position: non-static; z-index: 0 | auto</div>
    <div class="inline-block">inline element</div>
    <div class="float">float element</div>
    <div class="block-element"></div>
    <div class="z-index-negative">z-index: -1</div>
</div>
```

```css
.container {
    position: relative;
    z-index: 0;
    overflow: auto;
    width: 600px;
    height: 400px;
    border: 1px solid #fffcf9;
    border-radius: 2px;
    background: #fffcf9;
}

.container > div {
    width: 400px;
    height: 200px;
    font-size: 22px;
    line-height: 2.0;
    text-align: center;
    color: rgba(255,255,255,.95);
    border-radius: 2px;
}

[class|='z-index'] {
    position: absolute;
    top: 0;
    left: 0;
}

.z-index-positive {
    z-index: 1;
    margin: 200px 0 0 200px;
    background-color: #ffbfab;
}

.z-index-zero {
    z-index: 0;
    margin: 160px 0 0 160px;
    background-color: #f37262;
}

.inline-block {
    display: inline-block;
    margin: 120px 0 0 -360px;
    background: #fbc64d;
}

.float {
    float: left;
    margin: 80px 0 0 80px;
    background: #79b0a1;
}

.block-element {
    margin: -280px 0 120px 40px;
    background: #766ca1;
}

.block-element:before {
    position: relative;
    top: -240px;
    content: 'block element';
}

.z-index-negative {
    z-index: -1;
    background: #5c3554;
}
```
